# Generated by Django 4.0.4 on 2022-05-09 06:51

import analyzer_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file_location',
            field=models.FileField(max_length=30, upload_to=analyzer_app.models.upload_to_path),
        ),
    ]
